function SampleShows ()
{
}

var titles = [
    // IMDB top rated TV shows
    "band of brothers",
    "archer",
    "planet earth",
    "breaking bad",
    "game of thrones",
    "the wire",
    "cosmos a spacetime odyssey",
    "cosmos",
    "rick and morty",
    "the civil war",
    "the sopranos",
    "sherlock",
    "the world at war",
    "life",
    "avatar the last airbender",
    "last week tonight with john oliver",
    "true detective",
    "firefly",
    "the decalogue",
    "human planet",
    "the twilight zone",
    "the blue planet",
    "fullmetal alchemist brotherhood",
    "sarabhai vs sarabhai",
    "tvf pitchers",
    "one punch man wanpanman",
    "fargo",
    "frozen planet",
    "pride and prejudice",
    "batman the animated series",
    "cowboy bebop",
    "death note",
    "arrested development",
    "house of cards",
    "das boot",
    "monty python's flying circus",
    "over the garden wall",
    "narcos",
    "making a murderer",
    "twin peaks",
    "i claudius",
    "seinfeld",
    "friends",
    "freaks and geeks",
    "only fools and horses",
    "rome",
    "blackadder goes forth",
    "the simpsons",
    "fawlty towers",
    "the jinx the life and deaths of robert durst",
    "oz",
    "top gear",
    "hunter x hunter",
    "nathan for you",
    "from the earth to the moon",
    "long way round",
    "dragon ball z",
    "south park",
    "daredevil",
    "gravity falls",
    "black mirror",
    "house m.d.",
    "attack on titan",
    "the daily show",
    "better call saul",
    "dragon ball z",
    "six feet under",
    "it's always sunny in philadelphia",
    "dexter",
    "deadwood",
    "chappelle's show",
    "the adventures of sherlock holmes",
    "the office",
    "lonesome dove",
    "mr. robot",
    "the west wing",
    "battlestar galactica",
    "the x-files",
    "the thick of it",
    "q.i.",
    "black adder",
    "peaky blinders",
    "the shield",
    "one piece",
    "doctor who",
    "through the wormhole",
    "curb your enthusiasm",
    "black adder the third",
    "ash vs evil dead",
    "mystery science theater three thousand",
    "spaced",
    "brass eye",
    "berserk",
    "downton abbey",
    "fullmetal alchemist",
    "impractical jokers",
    "shameless",
    "generation kill",
    "adventure time",
    "battlestar galactica",
    "louie",
    "house of cards",
    "star trek the next generation",
    "yes minister",
    "john adams",
    "dr. horrible's sing-along blog",
    "mad men",
    "samurai champloo",
    "the angry video game nerd",
    "flight of the conchords",
    "the colbert report",
    "father ted",
    "dragon ball",
    "spartacus gods of the arena",
    "the bugs bunny show",
    "justified",
    "parks and recreation",
    "dragon ball",
    "friday night lights",
    "monster",
    "alfred hitchcock presents",
    "the office",
    "boardwalk empire",
    "young justice",
    "homicide life on the street",
    "the prisoner",
    "justice league",
    "whose line is it anyway",
    "coupling",
    "neon genesis evangelion",
    "kardes payi",
    "suits",
    "peep show",
    "rurouni kenshin wandering samurai",
    "the legend of korra",
    "the newsroom",
    "the bridge",
    "american crime story",
    "the venture bros",
    "luther",
    "the new batman adventures",
    "agatha christie poirot",
    "black books",
    "jesus of nazareth",
    "the it crowd",
    "i'm alan partridge",
    "futurama",
    "vikings",
    "mr. bean",
    "hannibal",
    "spartacus war of the damned",
    "gomorrah",
    "ghost in the shell stand alone complex",
    "sons of anarchy",
    "garth marenghi's darkplace",
    "mushi-shi",
    "modern family",
    "the knick",
    "community",
    "state of play",
    "police squad",
    "eleven twenty-two sixty-three",
    "permanent roommates",
    "parasyte the maxim",
    "x-men",
    "the walking dead",
    "entourage",
    "leyla and mecnun",
    "the muppet show",
    "brigada",
    "jeeves and wooster",
    "mr. show with bob and david",
    "scenes from a marriage",
    "endeavour",
    "wentworth prison",
    "utopia",
    "roots",
    "top gear",
    "silicon valley",
    "doctor who",
    "summer heights high",
    "bleak house",
    "twenty-four live another day",
    "generation war",
    "my mad fat diary",
    "yu yu hakusho ghost files",
    "trailer park boys",
    "red dwarf",
    "the kingdom",
    "hellsing ultimate",
    "supernatural",
    "borgen",
    "terriers",
    "happy valley",
    "the league of gentlemen",
    "i love lucy",
    "the inbetweeners",
    "extras",
    "broad city",
    "southland",
    "samurai jack",
    "lost",
    "mash",
    "boston legal",
    "fringe",
    "jane eyre",
    "prison break",
    "the dick van dyke show",
    "homeland",
    "scrubs",
    "a bit of fry and laurie",
    "twenty-four",
    "pushing daisies",
    "red versus blue the blood gulch chronicles",
    "trigun",
    "stargate sg one",
    "star trek",
    "olive kitteridge",
    "the night manager",
    "the adventures of brisco county junior",
    "anne of green gables",
    "cranford",
    "all in the family",
    "broadchurch",
    "the kids in the hall",
    "dragon ball z kai",
    "tengen toppa gurren lagann",
    "invader zim",
    "this is england eighty-eight",
    "foyle's war",
    "my so-called life",
    "blue mountain state",
    "billions",
    "wire in the blood",
    "life on mars",
    "banshee",
    "mythbusters",
    "the avengers earth's mightiest heroes",
    "person of interest",
    "orphan black",
    "the killing"
];


exports.titles = titles;